### PR TITLE
Feature/hub profile menu fix

### LINKED ISSUE #246: Create Profile Dropdown
## Overview

Create the Profile dropdown that shows up in the Profile Header component when a user's wallet is connected. This dropdown has two items: _Edit SELF_ID_ and _View Public_

Image

Image

## Details

- The _Edit SELF_ID_ is an external link to self.id 
- The _View Public_ is an internal link to the _/:address_ route for the Profile being viewed
- Can likely leverage the Dropdown component used in DAOhaus Connect

### PR DESCRIPTION
**Pull request by skuhlmann**
## GitHub Issue

[GitHub issue](https://github.com/HausDAO/daohaus-monorepo/issues/246).

fixes #246 

## Changes

- adds the self id external link destination
- applies full width bar to home nav to match designs
- fixes layout issues in public profile page
- adds toast to share copy to clipboard click

## Checks

Before making your PR, please check the following:

- [ ] Critical lint errors are resolved
- [ ] App runs locally
- [ ] App builds locally (run the build command for *any impacted package* and check for any errors before the PR)

### CODE REVIEW

File: apps/hub-app/src/pages/PublicProfilePage.tsx [hunk 1]
```diff
@@ -151,12 +169,12 @@ const PublicProfilePage = () => {
...
             {daoData.length < 1 ? (
               <DaoCountHeading>
-                <ParMd>No Dao memberships found</ParMd>
+                <ParMd>No DAO memberships found</ParMd>
               </DaoCountHeading>
             ) : (
               <DaoData>
                 <DaoCountHeading>
-                  {daoData.length} Total Dao {daoData.length === 1 ? '' : 's'}
+                  {daoData.length} Total DAO{daoData.length === 1 ? '' : 's'}
```
Comment (jordanlesich) [inline apps/hub-app/src/pages/PublicProfilePage.tsx:177]: V2 had a 'nouns' API that I think we should bring over. Doing this over and over again gets annoying. 

I'll make a ticket

File: apps/hub-app/src/pages/PublicProfilePage.tsx [hunk 2]
```diff
@@ -151,12 +169,12 @@ const PublicProfilePage = () => {
             <Profile />
             {daoData.length < 1 ? (
```
Comment (jordanlesich) [inline apps/hub-app/src/pages/PublicProfilePage.tsx:170]: Fine for now, because we're going to restructure this app anyways, but nested ternary

**Review by jordanlesich — APPROVED** [review]
