### PR TITLE
fix eth transfer encoding/decoding

### LINKED ISSUE #947: Add Error Message for Unverified Contracts
### Feature

Proposals

### App

[Admin](https://admin.daohaus.fun)

### Expected Behavior

Expect a message in the aaction data display

### Actual Behavior

Received error: No ABI found for this contract

### Steps to Reproduce

_No response_

### Browser

Brave

### Screenshots and Context

https://admin.daohaus.fun/#/molochV3/0x5/0x643e8e197de8760a23c64cf78bef7047084d5408/proposals/13

image

### PR DESCRIPTION
**Pull request by santteegt**
## GitHub Issue

Closes #947 

## Changes

Fix an encoding bug found when crafting eth transfers. Also fixes decoding issues in the UI

## Packages Added

None

## Checks

Before making your PR, please check the following:

- [X] Critical lint errors are resolved
- [X] App runs locally
- [X] App builds locally (run the build command for *any impacted package* and check for any errors before the PR)

### CODE REVIEW

File: libs/tx-builder-feature/src/utils/decoding.ts [hunk 1]
```diff
@@ -2,6 +2,7 @@ import { BigNumber, utils } from 'ethers';
 import {
   ArgType,
   CONTRACTS,
+  ENCODED_0X0_DATA,
   ValidNetwork,
   ZERO_ADDRESS,
```
Comment (skuhlmann) [inline libs/tx-builder-feature/src/utils/decoding.ts:7]: can we clean this unused import out?

**Review by skuhlmann — APPROVED** [review]

**Review by skuhlmann — APPROVED** [review]
